databases:
  # Base de données PostgreSQL managée
  - name: akal-db
    plan: free
    databaseName: akal_db
    user: akal_user
    ipAllowList: []

services:
  # Service Web Django (conteneurisé via Docker)
  - type: web
    name: akal-backend
    env: docker
    plan: free
   
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: akal-db
          property: connectionString
          
      - key: DJANGO_SETTINGS_MODULE
        value: akal.settings.prod
        
      - key: SECRET_KEY
        generateValue: true
        
      - key: PYTHONUNBUFFERED
        value: "1"