# Generated by Django 6.0.6 on 2026-06-26 11:41

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surface', models.DecimalField(decimal_places=2, help_text='Surface en hectares', max_digits=8)),
                ('statut_foncier', models.CharField(choices=[('melkia', 'Melkia'), ('soulaliya', 'Soulaliya'), ('guich', 'Guich'), ('habous', 'Habous'), ('immatricule', 'Immatriculé')], max_length=20)),
                ('acces_eau', models.CharField(choices=[('irriguee', 'Irriguée'), ('bour', 'Bour'), ('mixte', 'Mixte')], max_length=20)),
                ('topographie', models.CharField(choices=[('plat', 'Plat'), ('pentu', 'Pentu'), ('vallonne', 'Vallonné')], max_length=20)),
                ('acces_routier', models.CharField(choices=[('goudron', 'Goudron'), ('piste', 'Piste'), ('difficile', 'Difficile')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('contour', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Phase 2', null=True, srid=4326)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to='geo.commune')),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
                'db_table': 'parcelle',
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('titre', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, help_text='Prix en MAD', max_digits=12)),
                ('statut_annonce', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente'), ('en_ligne', 'En ligne'), ('archivee', 'Archivée'), ('vendue', 'Vendue')], default='brouillon', max_length=20)),
                ('loc_confidentielle', models.BooleanField(default=False)),
                ('vues', models.PositiveIntegerField(default=0)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='annonces.parcelle')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'db_table': 'annonce',
            },
        ),
        migrations.CreateModel(
            name='AgriScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_global', models.FloatField(blank=True, null=True)),
                ('sous_scores', models.JSONField(blank=True, null=True)),
                ('indice_confiance', models.FloatField(blank=True, null=True)),
                ('version_algo', models.CharField(max_length=50)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('parcelle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agriscore', to='annonces.parcelle')),
            ],
            options={
                'verbose_name': 'AgriScore',
                'verbose_name_plural': 'AgriScores',
                'db_table': 'agriscore',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='photos/')),
                ('ordre', models.IntegerField(default=0)),
                ('is_principale', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='annonces.annonce')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'db_table': 'photo',
                'ordering': ['ordre'],
            },
        ),
    ]
