# Generated by Django 6.0.6 on 2026-07-13 16:02

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='vues',
        ),
        migrations.RemoveField(
            model_name='parcelle',
            name='contour',
        ),
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together={('annonce', 'ordre')},
        ),
        migrations.CreateModel(
            name='DonneesGeo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contour', django.contrib.gis.db.models.fields.PolygonField(help_text='Contour géographique de la parcelle', srid=4326)),
                ('parcelle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donnees_geo', to='annonces.parcelle')),
            ],
            options={
                'verbose_name': 'Données Géo',
                'verbose_name_plural': 'Données Géo',
                'db_table': 'donnees_geo',
            },
        ),
        migrations.RemoveField(
            model_name='photo',
            name='is_principale',
        ),
        migrations.CreateModel(
            name='StatistiqueAnnonce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('vues', models.PositiveIntegerField(default=0)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to='annonces.annonce')),
            ],
            options={
                'verbose_name': 'Statistique Annonce',
                'verbose_name_plural': 'Statistiques Annonces',
                'db_table': 'statistique_annonce',
                'unique_together': {('annonce', 'date')},
            },
        ),
    ]
